### ISSUE TITLE
Energy dashboard

### ISSUE THREAD

**Issue by sgouw-hacs** [bgbraga/homeassistant-apsystems#4]
I want to use this for the new Energy dashboard.
Is it possible to add this?
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

**Comment by synack666** [comment]
You could help yourself, add state class, device class and last reset to the sensor via customize.yaml.
Did the update of counts work for you? See issue 3.

**Comment by sgouw-hacs** [comment]
Thanks for this.
I am pretty new to HA so I didn't that I could add it myself.
The update of counts doesn't seem to work, I only get new values when I restart.

**Comment by overas** [comment]
@synack666 
I added the state class, device class and last reset to the "sensor.apsystems_energy_day" using customize_glob.
[https://www.home-assistant.io/docs/configuration/customizing-devices/](url). 
It has been nice if this could be done from the plugin.

In the  configuration.yaml I put in this:
```
homeassistant:  
  customize_glob:
    sensor.apsystems_energy_day:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: measurement

**Comment by synack666** [comment]
should work if the counter updatet, hope this will be fixed soon.

**Comment by andrebbruno** [comment]
Hello @bgbraga - any plans on adding this within your integration?

thanks!

**Comment by andrebbruno** [comment]
> should work if the counter updatet, hope this will be fixed soon.

I was able to add this to the energy tab with the code you provided , hope this works now :) 

And hope mr Braga can have that updated in the integration itself.

thank you guys!

**Comment by andrebbruno** [comment]
> > should work if the counter updatet, hope this will be fixed soon.
> 
> I was able to add this to the energy tab with the code you provided , hope this works now :)
> 
> And hope mr Braga can have that updated in the integration itself.
> 
> thank you guys!

Edit: Issue fixed by removing "last reset and changing state class to total_increasing

thanks!

--------------------------------------------------

Guys,

Any idea why the counter went negative in the beggining of the day? 17,68 is what was produced yesterday.

This is what happened when I added the code @synack666 suggested.

thanks!

![image](https://user-images.githubusercontent.com/53448558/135492893-26ef034b-f3b3-4c33-b488-85d8613aecbd.png)

**Comment by skelgaard** [comment]
i have the same problem... did you find any solution for the negative start value ?

**Comment by andrebbruno** [comment]
> Issue fixed by removing "last reset and changing state class to total_increasing

Issue fixed by removing "last reset and changing state class to total_increasing

**Comment by skelgaard** [comment]
> > Issue fixed by removing "last reset and changing state class to total_increasing
> 
> Issue fixed by removing "last reset and changing state class to total_increasing

how do you do this ?

**Comment by andrebbruno** [comment]
> > > Issue fixed by removing "last reset and changing state class to total_increasing
> > 
> > 
> > Issue fixed by removing "last reset and changing state class to total_increasing
> 
> how do you do this ?

This is what I have in my config.yaml

![image](https://user-images.githubusercontent.com/53448558/147767837-345a8039-7539-4068-8040-366ce42ba1e9.png)

**Comment by skelgaard** [comment]
thanx, i will test that right away :)

**Comment by skelgaard** [comment]
thanx @andrebbruno that fixed it for me.... now i only need to figure out if there is some way to make it update every hour, as it seems to only update every 3 hours which makes bad graphs in the energy overview

**Comment by andrebbruno** [comment]
> thanx @andrebbruno that fixed it for me.... now i only need to figure out if there is some way to make it update every hour, as it seems to only update every 3 hours which makes bad graphs in the energy overview

cool! 3 Hours update is new to me ... mine updates every hour in the energy tab.

**Comment by skelgaard** [comment]
![billede](https://user-images.githubusercontent.com/13235820/147829839-dc936c6d-f542-426c-8225-91ab2e7a8bce.png)

**Comment by skelgaard** [comment]
well i found out why it doesn't update that often.... still looking into why
```
Logger: homeassistant.helpers.entity
Source: custom_components/apsystems/sensor.py:156
Integration: apsystems (documentation)
First occurred: 09:07:33 (34 occurrences)
Last logged: 11:52:28
Update for sensor.apsystems_energy_latest fails

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/apsystems/sensor.py", line 156, in async_update
    value = value[-1]
IndexError: list index out of range
```

**Comment by andrebbruno** [comment]
> well i found out why it doesn't update that often.... still looking into why
> 
> ```
> Logger: homeassistant.helpers.entity
> Source: custom_components/apsystems/sensor.py:156
> Integration: apsystems (documentation)
> First occurred: 09:07:33 (34 occurrences)
> Last logged: 11:52:28
> Update for sensor.apsystems_energy_latest fails
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
>     raise exc
>   File "/config/custom_components/apsystems/sensor.py", line 156, in async_update
>     value = value[-1]
> IndexError: list index out of range
> ```

yeah unfortunately we´re a bit out of luck, the developer seems DoA on his own integration

**Comment by skelgaard** [comment]
i'm working on fixing it, and if he doesn't come back, i will do a fork and fix it in that.

**Comment by synack666** [comment]
This sounds great and I thank you already!!!

**Comment by skelgaard** [comment]
looks like i got it fixed, i will post tomorrow if works there too.....
![image](https://user-images.githubusercontent.com/13235820/147954634-5e043f5b-1a3a-4bf3-bdc9-6ec9c62d6cc0.png)

**Comment by skelgaard** [comment]
i have made a fix and put it on my own page 
https://github.com/skelgaard/homeassistant-apsystems
please post there, if any other problems

**Comment by synack666** [comment]
Cant see how to post there, button "Issues" dont exist.
I installed today and from sunrise to now it works perfect.

**Comment by andrebbruno** [comment]
> i have made a fix and put it on my own page https://github.com/skelgaard/homeassistant-apsystems please post there, if any other problems

should I remove the current integration in HACS and add yours?

**Comment by synack666** [comment]
thats the way i do it, leave the config untouched, works

**Comment by synack666** [comment]
@skelgaard
How could we report issues, there is no issues button in your fork.
(only for interest, no problems found)

**Comment by skelgaard** [comment]
missing a checkmark... done now for both issues and discussions :)

**Comment by synack666** [comment]
pefrect
