### ISSUE TITLE
APSystem error in log dashboard

### ISSUE THREAD

**Issue by otello86** [bgbraga/homeassistant-apsystems#6]
Hi,
this error frequently  report in the HA log report :

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/config/custom_components/apsystems/sensor.py", line 156, in async_update
    value = value[-1]
IndexError: list index out of range

Do you know if there is a problem with my config or other ?

**Comment by skelgaard** [comment]
Go use my fork, it fixed that error for me https://github.com/skelgaard/homeassistant-apsystems
