### ISSUE TITLE
Not conection

### ISSUE THREAD

**Issue by carballada** [bgbraga/homeassistant-apsystems#9]
try different settings always with the same result

```
2022-03-26 21:34:01 ERROR (MainThread) [homeassistant.components.sensor] apsystems: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
await task
File "/config/custom_components/apsystems/sensor.py", line 146, in async_update
ap_data = await self._fetcher.data()
File "/config/custom_components/apsystems/sensor.py", line 253, in data
await self.run()
File "/config/custom_components/apsystems/sensor.py", line 221, in run
browser = await self.login()
File "/config/custom_components/apsystems/sensor.py", line 207, in login
browser.select_form(nr=0)
File "/usr/local/lib/python3.9/site-packages/mechanize/_mechanize.py", line 628, in select_form
raise BrowserStateError("not viewing HTML")
mechanize._mechanize.BrowserStateError: not viewing HTML
```

please, any ideas?

**Comment by andrebbruno** [comment]
> try different settings always with the same result
> 
> ```
> 2022-03-26 21:34:01 ERROR (MainThread) [homeassistant.components.sensor] apsystems: Error on device update!
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
> await entity.async_device_update(warning=False)
> File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
> await task
> File "/config/custom_components/apsystems/sensor.py", line 146, in async_update
> ap_data = await self._fetcher.data()
> File "/config/custom_components/apsystems/sensor.py", line 253, in data
> await self.run()
> File "/config/custom_components/apsystems/sensor.py", line 221, in run
> browser = await self.login()
> File "/config/custom_components/apsystems/sensor.py", line 207, in login
> browser.select_form(nr=0)
> File "/usr/local/lib/python3.9/site-packages/mechanize/_mechanize.py", line 628, in select_form
> raise BrowserStateError("not viewing HTML")
> mechanize._mechanize.BrowserStateError: not viewing HTML
> ```
> 
> please, any ideas?

do you have either ECU-R or ECU-B ? 

I´m using this other git as well, working great.

https://github.com/ksheumaker/homeassistant-apsystems_ecur
